name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 코드 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v3

    # JDK 17 설정
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    # gradlew 권한 설정
    - name: Set gradlew permissions
      run: |
        chmod +x ./gradlew 

    # gradle 빌드
    - name: Build with Gradle
      run: ./gradlew build

    - name: Set SSH key permissions
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Add known_hosts
      run: |
        ssh-keyscan -t ed25519 52.78.138.99 >> ~/.ssh/known_hosts

    #- name: 기존프로세스 종료
    #  run: |
    #    kill -9 $(ps -ef | grep devops | grep -v grep | head -n 1 | awk '{print $2}') || true

    #- name: Deploy to Server
    #  run: scp build/libs/*.jar ubuntu@52.78.138.99:~/app
    
    - name: Deploy with rsync
      run: |
        timeout 60s rsync -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" \
          -avz build/libs/*.jar ubuntu@52.78.138.99:~/app      


    - name: Run SSH commands
      run: |
        ssh -i ~/.ssh/id_ed25519 ubuntu@52.78.138.99 << 'EOF'
          pkill -f 'java -jar' || true
          nohup java -jar ~/app/devops-0.0.1-SNAPSHOT.jar > log.txt 2>&1 &
        EOF
