name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 코드 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v3

    # JDK 17 설정
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
        cache: gradle

    # gradlew 권한 설정
    - name: Set gradlew permissions
      run: |
        chmod +x ./gradlew 
        
    # Gradle 의존성 캐시 (추가 옵션; setup-java의 cache: gradle로도 충분)
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches/
          ~/.gradle/wrapper/
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-    

    # gradle 빌드 (병렬 및 on-demand 설정으로 빌드 속도 향상)
    - name: Build with Gradle
      run: ./gradlew build --parallel --configure-on-demand

    - name: Set SSH key permissions
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Add known_hosts
      run: |
        ssh-keyscan -t ed25519 43.200.173.46 >> ~/.ssh/known_hosts

    #- name: 기존프로세스 종료
    #  run: |
    #    kill -9 $(ps -ef | grep devops | grep -v grep | head -n 1 | awk '{print $2}') || true

    #- name: Deploy to Server
    #  run: scp build/libs/*.jar ubuntu@52.78.138.99:~/app
    
    - name: Deploy with rsync
      run: |
        timeout 60s rsync -e "ssh -c aes128-ctr -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" \
          -avz build/libs/*.jar ubuntu@43.200.173.46:~/app      


    - name: Run SSH commands
      run: |
        ssh -i ~/.ssh/id_ed25519 ubuntu@43.200.173.46 << 'EOF'
          pkill -f 'java -jar' || true
          nohup java -jar ~/app/devops-0.0.1-SNAPSHOT.jar > log.txt 2>&1 &
        EOF
